[project]
name = "to-do-list"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12"
dependencies = [
    "flask==3.1.2",
    "flask-dance==7.1.0",
    "flask-login==0.6.3",
    "flask-migrate==4.1.0",
    "flask-sqlalchemy==3.1.1",
    "psycopg2==2.9.10",
    "python-dotenv==1.1.1",
]
